version: '3'

services:
  slm:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./src/database/:/license-manager/src/database/
    environment:
      - WORKERS=2
      - THREADS=4
      - PORT=8000
    networks:
      - slm_default

networks:
  slm_default: