version: '3'

services:
  proxy:
    image: nginx:latest
    volumes:
      - ./nginx/certs/:/ssl/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx 
      - ./nginx/cache/:/etc/nginx/cache
    networks:
      - slm_default
    ports:
      - 80:80
      - 443:443

  slm:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./bin/database:/license-manager/bin/database
    environment:
      - WORKERS=2
      - THREADS=4
      - PORT=8000
    networks:
      - slm_default

networks:
  slm_default: