# .github/workflows/app.yaml
name: PyTest
on:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          cache: "pip" # caching pip dependencies

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install autopep8
          pip install pylint==2.15.3
  autopep8:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: setup
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          cache: "pip" # caching pip dependencies

      - name: Install dependencies
        run: |
          pip install autopep8
      - name: autopep8
        id: autopep8
        uses: peter-evans/autopep8@v1
        with:
          args: --recursive --in-place --aggressive --aggressive .

      - name: Fail if autopep8 made changes
        if: steps.autopep8.outputs.exit-code == 2
        run: exit 1

  pylint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: setup
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          cache: "pip" # caching pip dependencies

      - name: Install dependencies
        run: |
          pip install pylint==2.15.3
      - name: Analysing the code with pylint
        run: |
          pylint --fail-under 7.0 --recursive y --enable W --rcfile .pylintrc

  pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: setup
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          cache: "pip" # caching pip dependencies

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install autopep8
          pip install pylint==2.15.3
          
      - name: Run test suite
        run: |
          pytest -v
